[package]
name = "radicle-surf"
description = "A code surfing library for VCS file systems"
readme = "README.md"
version = "0.2.1"
authors = ["The Radicle Team <dev@radicle.xyz>"]
edition = "2018"
homepage = "https://github.com/radicle-dev/radicle-surf"
repository = "https://github.com/radicle-dev/radicle-surf"
license = "GPL-3.0-or-later"

[dependencies]
git2 = "0.12"
thiserror = "1.0"
nonempty = { git = "https://github.com/cloudhead/nonempty.git", rev = "9c65e9fec82b9089d3a76f867e4cc93ede76a5a9" }

[dev-dependencies]
pretty_assertions = "0.6"
proptest = "0.9"
