[package]
name = "radicle-surf"
version = "0.1.0"
authors = ["Fintan Halpenny <fintan.halpenny@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.10.1"
nonempty = "0.2.0"

[dev-dependencies]
pretty_assertions = "0.6.1"
proptest = "0.9.4"
