env:
  DOCKER_IMAGE: "gcr.io/opensourcecoin/radicle-surf-build@sha256:0b46adec76130f9fb2feab221d87f793f565a65b2b171f0dbd546e4320a6475c"
  DOCKER_FILE: .buildkite/docker/rust/Dockerfile

steps:
- label: "Build, lint, test"
  commands:
  - "ci/run"
  agents:
    production: "true"
    platform: "linux"
