env:
  DOCKER_IMAGE: "gcr.io/opensourcecoin/radicle-surf-build:8c5e5e90064cb89f5faeedfe2874cbc3efbe260c"
  DOCKER_FILE: .docker/build/Dockerfile

steps:
- label: "Tests"
  command:
  # Ensure we have fetched the remote info in submodule
  - git submodule foreach "git fetch origin"
  - "cargo test --all"
  agents:
    production: "true"
    platform: "linux"
