env:
  DOCKER_IMAGE: gcr.io/opensourcecoin/radicle-surf-build
  DOCKER_FILE: .buildkite/docker/rust-nightly/Dockerfile

steps:
- label: "Build, lint, test"
  commands:
  - "ci/run"
  agents:
    production: "true"
    platform: "linux"
