[package]
name = "radicle-surf"
description = "A code surfing library for VCS file systems"
readme = "README.md"
version = "0.6.1"
authors = ["The Radicle Team <dev@radicle.xyz>"]
edition = "2018"
homepage = "https://github.com/radicle-dev/radicle-surf"
repository = "https://github.com/radicle-dev/radicle-surf"
license = "GPL-3.0-or-later"

include = [
    "**/*.rs",
    "Cargo.toml",
    "data/git-platinum.tgz",
]

[features]
serialize = ["serde"]
# NOTE: testing `test_submodule_failure` on GH actions
# is painful since it uses this specific repo and expects
# certain branches to be setup. So we use this feature flag
# to ignore the test on CI.
gh-actions = []

[dependencies]
either = "1.5"
nom = "6"
nonempty = "0.5"
regex = "1.3"
serde = { features = ["serde_derive"], optional = true, version = "1" }
thiserror = "1.0"

[dependencies.git2]
version = ">= 0.12"
default-features = false
features = []

[dev-dependencies]
pretty_assertions = "0.6"
proptest = "0.9"
criterion = "0.3"
serde_json = "1"

[build-dependencies]
anyhow = "1.0"
flate2 = "1"
tar = "0.4"

[[bench]]
name = "last_commit"
harness = false
